### PR TITLE
emit `obj-loaded` event when obj is loaded

### PR DESCRIPTION
**Pull request by tjiahen**
maybe we can put a better name. Will update the documentation if you think it is a good idea.

### CODE REVIEW

**Comment by donmccurdy** [comment]
I like the idea of having an event when the model loads! .OBJ+.MTL support has been merged into the main aframe project's _dev_ branch, in the [default loader component](https://github.com/aframevr/aframe/blob/dev/src/components/loader.js), so it might be best to make a pull request there and get feedback about the event name – i'd like to keep this consistent with the default loader.

The aframe folks might have more thoughts about the name, but my idea would be:

``` javascript
this.el.emit('load', {format: 'obj'}, false);
```

The format might not even be needed, since you can't really have more than one loader on the element, and the event doesn't need to bubble.

**Comment by donmccurdy** [comment]
Also the loader component might be renamed soon https://github.com/aframevr/aframe/pull/845 /cc @ngokevin

**Comment by donmccurdy** [comment]
Thanks for bringing this up! I ran this by the A-Frame folks and have decided to go with a `model-loaded` event. It's been merged into A-Frame's v0.2.0 / dev branch, and is merged here as well.

**Comment by tjiahen** [comment]
+1

**Pull request closed without merging**
